# ======================================================
#         NoStructureBlock - Konfiguracja
# ======================================================

settings:
  bypass-permission: "nostructureblock.admin"  # Uprawnienie pozwalające ominąć blokadę

blocked-blocks:
  enabled: true
  
  # Lista bloków, których stawianie jest cicho blokowane:
  list:
    - STRUCTURE_BLOCK          # Structure Block
    - STRUCTURE_VOID           # Pustka strukturalna
    - COMMAND_BLOCK
    - CHAIN_COMMAND_BLOCK
    - REPEATING_COMMAND_BLOCK
    - BARRIER
    - JIGSAW
    - LIGHT`
